[profile.default]
  evm_version = "paris"
  optimizer = true
  optimizer_runs = 50
  via_ir = true
  solc_version = "0.8.26"
  verbosity = 3
  gas_reports = ["Staking", "DelegateStaking", "RewardsDistributor"]

[profile.ci]
  fuzz = { runs = 5000 }
  invariant = { runs = 1000 }

[profile.lite]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"
  testnet = "${TESTNET_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
testnet = { key = "${ETHERSCAN_MAINNET_KEY}", chain = "11155111" }

