[profile.default]
  evm_version = "paris"
  optimizer = true
  optimizer_runs = 10_000_000
  solc_version = "0.8.25"
  verbosity = 3

[profile.ci]
  fuzz = { runs = 5000 }
  invariant = { runs = 1000 }

[profile.lite]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

